/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class Calculate {
  public int sum(int x, int y) {
    return x + y;
  }

  public float avg(int x, int y) {
    return (float) x / y;
  }
}
